name: 'music-spot'
version: '3.8'

services:
    db:
        container_name: music-db
        image: postgres:16
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: music_api_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - default

volumes:
    postgres_data:
