# Generated by Django 5.1.1 on 2024-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
