"""Generated by Django 5.1.1 on 2024-10-31 03:40."""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="libraries",
        ),
        migrations.RemoveField(
            model_name="album",
            name="libraries",
        ),
        migrations.DeleteModel(
            name="Library",
        ),
    ]
