"""Generated by Django 5.1.1 on 2024-10-03 14:32."""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("api", "0002_appuser_spotify_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="appuser",
            name="spotify_display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="spotify_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
