"""Generated by Django 5.1.1 on 2024-10-07 16:26."""

from django.db import migrations

import api.models.users


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_service_remove_appuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="appuser",
            managers=[
                ("objects", api.models.users.AppUserManager()),
            ],
        ),
    ]
