# Generated by Django 5.1.1 on 2024-10-31 20:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_playlist_libraries_remove_album_libraries_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="album",
            managers=[
                ("sync", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="artist",
            managers=[
                ("sync", django.db.models.manager.Manager()),
            ],
        ),
    ]
