# Generated by Django 5.1.1 on 2024-10-31 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_album_managers_alter_artist_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computation",
                to="api.album",
            ),
        ),
        migrations.AlterField(
            model_name="computation",
            name="playlist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computation",
                to="api.playlist",
            ),
        ),
    ]
