# Generated by Django 5.1.1 on 2024-10-09 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_appuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("album_type", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("copyright", models.CharField(blank=True, max_length=255)),
                ("release_year", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True)),
                ("spotify_follower_count", models.IntegerField(blank=True)),
                (
                    "album_ids",
                    models.ManyToManyField(related_name="artists", to="api.album"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artist_ids",
            field=models.ManyToManyField(related_name="albums", to="api.artist"),
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "album_ids",
                    models.ManyToManyField(related_name="genres", to="api.album"),
                ),
                (
                    "artist_ids",
                    models.ManyToManyField(related_name="genres", to="api.artist"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="genre_ids",
            field=models.ManyToManyField(related_name="artists", to="api.genre"),
        ),
        migrations.AddField(
            model_name="album",
            name="genre_ids",
            field=models.ManyToManyField(related_name="albums", to="api.genre"),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("features", models.JSONField(default=dict)),
                ("duration", models.IntegerField()),
                (
                    "playlist_ids",
                    models.ManyToManyField(related_name="tracks", to="api.playlist"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="track_ids",
            field=models.ManyToManyField(related_name="playlists", to="api.track"),
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "album_ids",
                    models.ManyToManyField(related_name="libraries", to="api.album"),
                ),
                (
                    "artist_ids",
                    models.ManyToManyField(related_name="libraries", to="api.artist"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playlist_ids",
                    models.ManyToManyField(related_name="libraries", to="api.playlist"),
                ),
                (
                    "track_ids",
                    models.ManyToManyField(related_name="libraries", to="api.track"),
                ),
            ],
        ),
    ]
