# Generated by Django 5.1.1 on 2024-10-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_album_playlist_artist_album_artist_ids_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="owner_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
