# Generated by Django 5.1.1 on 2024-10-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_computation_album_alter_computation_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.album'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='playlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.playlist'),
        ),
    ]
