# Generated by Django 5.1.1 on 2024-10-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_track_features_track_album_id_analysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
