# Generated by Django 5.1.1 on 2024-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_track_album_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="artist_ids",
            new_name="artist",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="album_ids",
            new_name="albums",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="artist_ids",
            new_name="artists",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="album_ids",
            new_name="albums",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="artist_ids",
            new_name="artists",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="playlist_ids",
            new_name="playlists",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="track_ids",
            new_name="tracks",
        ),
        migrations.RenameField(
            model_name="playlist",
            old_name="track_ids",
            new_name="tracks",
        ),
        migrations.RemoveField(
            model_name="album",
            name="genre_ids",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="album_ids",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="genre_ids",
        ),
        migrations.RemoveField(
            model_name="track",
            name="playlist_ids",
        ),
        migrations.AlterField(
            model_name="album",
            name="album_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="spotify_follower_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="public",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="shared",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
