# Generated by Django 5.1.1 on 2024-10-11 19:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_artist_ids_album_artist_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="playlist",
            managers=[
                ("sync", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="analysis",
            old_name="playlist_id",
            new_name="playlist",
        ),
        migrations.RenameField(
            model_name="analysis",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="user_id",
            new_name="user",
        ),
    ]
