# Generated by Django 5.1.1 on 2024-10-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_playlist_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="user_id",
            new_name="user",
        ),
    ]
