"""Generated by Django 5.1.1 on 2024-10-11 20:04."""

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):  # noqa
    model_names = ["Album", "Artist", "Track"]

    for model_name in model_names:
        model = apps.get_model("api", model_name.lower())
        model.objects.all().update(identity=uuid.uuid4())

    model = apps.get_model("api", "playlist")
    model.sync.all().update(identity=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_auto_20241011_2004"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
