# Generated by Django 5.1.1 on 2024-10-11 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_auto_20241011_2004"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="playlist",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="album",
            name="id",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="id",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="id",
        ),
        migrations.RemoveField(
            model_name="track",
            name="id",
        ),
        migrations.AlterField(
            model_name="album",
            name="identity",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="identity",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="identity",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="identity",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
