# Generated by Django 5.1.1 on 2024-10-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_playlist_managers_remove_album_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="identity",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="identity",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="playlist",
            old_name="identity",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="track",
            old_name="identity",
            new_name="id",
        ),
    ]
