# Generated by Django 5.1.1 on 2024-10-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_playlist_tracks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="artists",
        ),
    ]
