# Generated by Django 5.1.1 on 2024-10-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_album_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(related_name="albums", to="api.artist"),
        ),
    ]
