# Generated by Django 5.1.1 on 2024-10-12 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_track_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracks",
                to="api.album",
            ),
        ),
    ]
