# Generated by Django 5.1.1 on 2024-10-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_track_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="playlist",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="tracks",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="user",
        ),
        migrations.RemoveField(
            model_name="trackfeatures",
            name="track",
        ),
    ]
