# Generated by Django 5.1.1 on 2024-10-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_analysis_playlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackfeatures",
            old_name="identity",
            new_name="id",
        ),
    ]
