# Generated by Django 5.1.1 on 2024-10-12 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_rename_identity_trackfeatures_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="id",
        ),
        migrations.AddField(
            model_name="analysis",
            name="identity",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
