# Generated by Django 5.1.1 on 2024-10-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_remove_analysis_id_analysis_identity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="identity",
            new_name="id",
        ),
    ]
