# Generated by Django 5.1.1 on 2024-10-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_rename_identity_analysis_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="tracks",
        ),
    ]
