# Generated by Django 5.1.1 on 2024-10-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_analysis_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="tracks",
            field=models.ManyToManyField(related_name="analyses", to="api.track"),
        ),
    ]
