# Generated by Django 5.1.1 on 2024-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_analysis_tracks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist",
            options={
                "ordering": ["-is_synced", "-updated_at", "-is_analyzed", "-created_at"]
            },
        ),
        migrations.RemoveField(
            model_name="library",
            name="playlists",
        ),
        migrations.AddField(
            model_name="playlist",
            name="libraries",
            field=models.ManyToManyField(related_name="playlists", to="api.library"),
        ),
        migrations.AlterUniqueTogether(
            name="playlist",
            unique_together={("spotify_id", "user")},
        ),
    ]
