# Generated by Django 5.1.1 on 2024-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_playlist_options_remove_library_playlists_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="artists",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="tracks",
        ),
        migrations.AddField(
            model_name="artist",
            name="albums",
            field=models.ManyToManyField(related_name="artists", to="api.album"),
        ),
        migrations.AddField(
            model_name="track",
            name="playlists",
            field=models.ManyToManyField(related_name="tracks", to="api.playlist"),
        ),
    ]
