# Generated by Django 5.1.1 on 2024-10-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_remove_album_artists_remove_playlist_tracks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="access_token",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="refresh_token",
            field=models.CharField(),
        ),
    ]
