# Generated by Django 5.1.1 on 2024-10-14 03:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import api.models.analysis
import api.serializers
import api.serializers.validation


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_alter_appuser_access_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist",
            options={
                "ordering": ["-is_synced", "-is_analyzed", "-updated_at", "-created_at"]
            },
        ),
        migrations.CreateModel(
            name="Computation",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        validators=[
                            api.serializers.validation.ComputationValidator.validate_data
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="api.analysis",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computation",
                        to="api.playlist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
