# Generated by Django 5.1.1 on 2024-10-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_alter_playlist_options_computation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="albums",
        ),
        migrations.AddField(
            model_name="album",
            name="libraries",
            field=models.ManyToManyField(related_name="albums", to="api.library"),
        ),
    ]
