# Generated by Django 5.1.1 on 2024-10-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_remove_library_albums_album_libraries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="albums",
        ),
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(related_name="albums", to="api.genre"),
        ),
    ]
