# Generated by Django 5.1.1 on 2024-10-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_remove_genre_artists_artist_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_analyzed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="is_synced",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="is_synced",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="is_analyzed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="is_synced",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
