# Generated by Django 5.1.1 on 2024-10-15 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_album_is_analyzed_album_is_synced_artist_is_synced_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
