# Generated by Django 5.1.1 on 2024-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_track_options_playlist_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
