"""Generated by Django 5.1.1 on 2024-10-31 03:40."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0003_remove_playlist_libraries_remove_album_libraries_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "albums",
                    models.ManyToManyField(related_name="libraries", to="api.album"),
                ),
                (
                    "artists",
                    models.ManyToManyField(related_name="libraries", to="api.artist"),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="libraries", to="api.genre"),
                ),
                (
                    "playlists",
                    models.ManyToManyField(related_name="libraries", to="api.playlist"),
                ),
                (
                    "tracks",
                    models.ManyToManyField(related_name="libraries", to="api.track"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
