"""Generated by Django 5.1.1 on 2024-11-03 03:47."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
        ("live", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="operation",
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["user", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="acknowledgement",
            name="client",
        ),
        migrations.RemoveField(
            model_name="acknowledgement",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.AddField(
            model_name="notification",
            name="group_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification",
                to="django_celery_results.groupresult",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="task_result",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.AlterField(
            model_name="acknowledgement",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acknowledgement",
                to="live.notification",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("task_result__isnull", False),
                    ("group_result__isnull", False),
                    _connector="OR",
                ),
                name="notification_task_or_group",
            ),
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Operation",
        ),
    ]
