"""Generated by Django 5.1.1 on 2024-11-03 06:51."""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0003_remove_operation_resource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="extras",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
