# Generated by Django 5.1.1 on 2024-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0004_notification_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="operation",
            field=models.CharField(
                blank=True,
                choices=[("sync", "Sync"), ("analyze", "Analyze")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="resource",
            field=models.CharField(
                blank=True,
                choices=[
                    ("playlist", "Playlist"),
                    ("album", "Album"),
                    ("track", "Track"),
                    ("artist", "Artist"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="resource_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
