# Generated by Django 5.1.1 on 2024-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0005_notification_operation_notification_resource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="task_id",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name="notification",
            name="operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sync", "Sync"),
                    ("analyze", "Analyze"),
                    ("full_sync", "Full Sync"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="resource",
            field=models.CharField(
                blank=True,
                choices=[
                    ("playlist", "Playlist"),
                    ("album", "Album"),
                    ("track", "Track"),
                    ("artist", "Artist"),
                    ("library", "Library"),
                ],
                max_length=16,
            ),
        ),
    ]
