# Generated by Django 5.1.1 on 2024-11-04 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0006_notification_task_id_alter_notification_operation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_task_or_group",
        ),
    ]
